import html2pdf from 'html2pdf.js';

/**
 * Generate a PDF from an HTML string rendered inside an iframe.
 * Uses INLINE STYLES only because html2canvas ignores <style> tags.
 */
export const exportToPdf = async (htmlContent, filename = 'document.pdf') => {
  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.top = '0';
  iframe.style.left = '0';
  iframe.style.width = '800px';
  iframe.style.height = '100%';
  iframe.style.zIndex = '-1';
  iframe.style.opacity = '0';
  document.body.appendChild(iframe);

  const iframeDoc = iframe.contentDocument || iframe.contentWindow.document;
  iframeDoc.open();
  iframeDoc.write(`<!DOCTYPE html>
<html>
<head><meta charset="utf-8" /></head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #1f2937; background: #fff; padding: 32px 38px; font-size: 12.5px; line-height: 1.8; -webkit-print-color-adjust: exact; print-color-adjust: exact;">
  ${htmlContent}
  <div style="margin-top: 36px; padding-top: 12px; border-top: 1px solid #e5e7eb; text-align: center; font-size: 9px; color: #9ca3af; letter-spacing: 0.3px;">
    Generated by UniAct Knowledge System &bull; ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`);
  iframeDoc.close();

  await new Promise(resolve => setTimeout(resolve, 600));

  const opt = {
    margin:       [10, 10, 10, 10],
    filename:     filename,
    image:        { type: 'jpeg', quality: 0.98 },
    html2canvas:  { scale: 2, useCORS: true },
    jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' },
    pagebreak:    { mode: ['css', 'legacy'] }
  };

  try {
    await html2pdf().set(opt).from(iframeDoc.body).save();
  } catch (err) {
    console.error('PDF Export Error:', err);
  } finally {
    document.body.removeChild(iframe);
  }
};

/* ════════════════════════════════════════════════════
   INLINE-STYLED HTML BUILDERS
   ════════════════════════════════════════════════════ */

/** Document header block (exam, summary, mindmap) */
export function buildHeader(title, metaLines) {
  return `
    <div style="text-align:center; padding:18px 24px 16px; margin-bottom:28px; background:#f0f0ff; border:1px solid #ddd5f5; border-radius:8px; border-top:4px solid #6366f1;">
      <div style="font-size:20px; font-weight:700; color:#1e1b4b; margin-bottom:10px;">${title}</div>
      <div style="font-size:11px; color:#6b7280; line-height:1.7;">${metaLines}</div>
    </div>`;
}

/** Answer Key header */
export function buildAnswerKeyHeader() {
  return `
    <div style="text-align:center; padding:16px 24px 14px; margin-bottom:22px; background:#ecfdf5; border:1px solid #bbf7d0; border-radius:8px; border-top:4px solid #22c55e;">
      <div style="font-size:18px; font-weight:700; color:#166534;">📋 Answer Key</div>
    </div>`;
}

/** Section title (e.g. "Section A — MCQ") */
export function buildSectionTitle(text) {
  return `<div style="font-size:14px; font-weight:700; color:#1e1b4b; margin-top:26px; margin-bottom:14px; padding:8px 14px; background:#f5f3ff; border-left:4px solid #6366f1; border-radius:0 6px 6px 0;">${text}</div>`;
}

/**
 * Robust Markdown → inline-styled HTML converter.
 */
export function markdownToHtml(md) {
  if (!md) return '';
  let html = md;

  // Code blocks
  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_, lang, code) => {
    return `\n<div style="background:#1e293b; color:#e2e8f0; padding:14px 16px; border-radius:6px; margin:12px 0; font-size:11px; line-height:1.6; font-family:Consolas,monospace; white-space:pre-wrap; overflow-wrap:break-word;">${escHtml(code.trimEnd())}</div>\n`;
  });

  // Inline code
  html = html.replace(/`([^`\n]+)`/g,
    '<span style="background:#f1f5f9; padding:1px 5px; border-radius:3px; font-size:11px; font-family:Consolas,monospace; color:#7c3aed;">$1</span>');

  // Horizontal rules
  html = html.replace(/^---+$/gm, '<hr style="border:none; border-top:1px solid #e5e7eb; margin:18px 0;"/>');

  // Headers
  html = html.replace(/^#### (.+)$/gm,
    '<div style="font-size:12.5px; font-weight:600; color:#4b5563; margin-top:14px; margin-bottom:6px;">$1</div>');
  html = html.replace(/^### (.+)$/gm,
    '<div style="font-size:13.5px; font-weight:600; color:#4338ca; margin-top:18px; margin-bottom:8px;">$1</div>');
  html = html.replace(/^## (.+)$/gm,
    '<div style="font-size:15px; font-weight:700; color:#312e81; margin-top:22px; margin-bottom:10px; padding-bottom:5px; border-bottom:1px solid #ede9fe;">$1</div>');
  html = html.replace(/^# (.+)$/gm,
    '<div style="font-size:18px; font-weight:700; color:#1e1b4b; margin-top:26px; margin-bottom:12px; padding-bottom:7px; border-bottom:2px solid #e5e7eb;">$1</div>');

  // Bold + Italic
  html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong style="font-weight:700;"><em>$1</em></strong>');
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong style="font-weight:700; color:#111827;">$1</strong>');
  html = html.replace(/(?<!\*)\*([^*\n]+)\*(?!\*)/g, '<em style="font-style:italic; color:#4b5563;">$1</em>');

  // Blockquotes
  html = html.replace(/^> (.+)$/gm,
    '<div style="border-left:4px solid #8b5cf6; padding:8px 14px; margin:12px 0; background:#faf5ff; color:#4b5563; font-style:italic; border-radius:0 5px 5px 0;">$1</div>');

  // Tables
  html = html.replace(/((?:^\|.+\|$\n?)+)/gm, (tableBlock) => {
    const rows = tableBlock.trim().split('\n');
    if (rows.length < 2) return tableBlock;
    let table = '<table style="width:100%; border-collapse:collapse; margin:14px 0; font-size:11.5px;">';
    rows.forEach((row, idx) => {
      if (/^\|[\s\-:|]+\|$/.test(row)) return;
      const cells = row.split('|').filter((c, i, a) => i > 0 && i < a.length - 1);
      const isHeader = idx === 0;
      table += '<tr>';
      cells.forEach(cell => {
        if (isHeader) {
          table += `<td style="border:1px solid #d1d5db; padding:7px 10px; background:#f3f4f6; font-weight:700;">${cell.trim()}</td>`;
        } else {
          table += `<td style="border:1px solid #d1d5db; padding:7px 10px;">${cell.trim()}</td>`;
        }
      });
      table += '</tr>';
    });
    table += '</table>';
    return table;
  });

  // Lists
  const lines = html.split('\n');
  let result = [];
  let inUl = false, inOl = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const ulMatch = line.match(/^[\s]*[\-\*]\s+(.+)$/);
    const olMatch = line.match(/^[\s]*\d+\.\s+(.+)$/);

    if (ulMatch) {
      if (inOl) { result.push('</ol>'); inOl = false; }
      if (!inUl) { result.push('<ul style="margin-left:22px; margin-bottom:14px; padding-left:4px;">'); inUl = true; }
      result.push(`<li style="margin-bottom:6px; padding-left:4px;">${ulMatch[1]}</li>`);
    } else if (olMatch) {
      if (inUl) { result.push('</ul>'); inUl = false; }
      if (!inOl) { result.push('<ol style="margin-left:22px; margin-bottom:14px; padding-left:4px;">'); inOl = true; }
      result.push(`<li style="margin-bottom:6px; padding-left:4px;">${olMatch[1]}</li>`);
    } else {
      if (inUl) { result.push('</ul>'); inUl = false; }
      if (inOl) { result.push('</ol>'); inOl = false; }
      result.push(line);
    }
  }
  if (inUl) result.push('</ul>');
  if (inOl) result.push('</ol>');
  html = result.join('\n');

  // Key-term pattern: lines like "<strong>Bold Term:</strong> description"
  html = html.replace(
    /^(<strong[^>]*>[^<]+:<\/strong>\s*.+)$/gm,
    '<div style="margin-bottom:10px; padding:9px 14px; background:#fafbfd; border-left:3px solid #a78bfa; border-radius:0 5px 5px 0;">$1</div>'
  );

  // Paragraphs
  html = html.split('\n\n').map(block => {
    block = block.trim();
    if (!block) return '';
    if (/^<(div|ul|ol|li|pre|table|tr|hr)/.test(block)) return block;
    return `<div style="margin-bottom:12px; line-height:1.85; text-align:justify;">${block.replace(/\n/g, '<br/>')}</div>`;
  }).join('\n');

  return html;
}

function escHtml(str) {
  return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}
